### ISSUE TITLE
External clock and reset signals bleeding into power LED

### ISSUE THREAD

**Issue by RomainWELKER** [hotchk155/matrix-seq-firmware2#24]
I noticed that the external clock and reset signals bleed into the power LED when the Noodlebox is turned off, and even when the power supply is disconnected.

**Comment by hotchk155** [comment]
Yeah - the reason for this is that the input voltages are "clamped" through resistors and diodes to the power rails (to protects the input circuit from voltages above 5V). However when the Noodlebox power is off, enough of this incoming voltage reaches the power rails to light the LED, although the voltage reaching the power rails is a lot less than the input voltage due to the impedance of the input resistor and loading of the other components.
